### ISSUE TITLE
Espinita not working when used in multiple models.

### ISSUE THREAD

**Issue by ravindrakanak017** [continuum/espinita#17] opened 2015-01-30 07:25 UTC
I have tested espinita with mu user table and it works properly, but when i used it in another model it through while restarting the server "undefined local variable or method 'auditable' for class" . What could be the problem in using auditing for multiple models same time.

**Comment by ravindrakanak017** [comment] 2015-01-30 09:39
Issue is fixed some how but i am still amazed with the strange behavior. In some places i have to use 
"include Espinita::AuditorBehavior " above auditable and on some places it works without it.

**Comment by michelson** [comment] 2015-08-06 14:27
can't reproduce this, would be great if you can give an example or a test case , for the meanwhile I'm going to close this issue

**Closed by michelson** 2015-08-06 14:27 UTC

**Comment by ravindrakanak017** [comment] 2015-08-07 05:49
I have resolved the issue myself now it's working properly on my end. Thanks
